"""create_all_tables

Revision ID: 0d9b21839fe5
Revises: bb84e7abad98
Create Date: 2026-03-15 05:55:44.064839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d9b21839fe5'
down_revision: Union[str, None] = 'bb84e7abad98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'STAFF', name='admin_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recurrence_weeks_default', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availability_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocked_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'BANNED', name='contact_status'), nullable=False),
    sa.Column('reminder_preference_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('admin_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('ACCOUNT_SUSPENDED', 'STRIKE_WARNING', 'REMINDER_FAILED', 'CALENDAR_ERROR', 'NEW_BOOKING', 'OPT_OUT', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_consent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('UNCONTACTED', 'PENDING', 'OPTED_IN', 'OPTED_OUT', 'BLOCKED', name='consent_status'), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_in_method', sa.Enum('SMS_REPLY', 'ADMIN_MANUAL', 'IMPORTED', name='opt_in_method'), nullable=True),
    sa.Column('opt_out_method', sa.Enum('SMS_STOP', 'SMS_REPLY', 'ADMIN_MANUAL', name='opt_out_method'), nullable=True),
    sa.Column('last_status_change_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_phone')
    )
    op.create_table('contact_consent_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.Enum('UNCONTACTED', 'PENDING', 'OPTED_IN', 'OPTED_OUT', 'BLOCKED', name='consent_status'), nullable=False),
    sa.Column('new_status', sa.Enum('UNCONTACTED', 'PENDING', 'OPTED_IN', 'OPTED_OUT', 'BLOCKED', name='consent_status'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by_phone', sa.String(length=20), nullable=True),
    sa.Column('changed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_strikes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('strike_number', sa.Integer(), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('IRRELEVANT', 'ABUSIVE', 'INJECTION', name='strike_classification'), nullable=False),
    sa.Column('screener_method', sa.Enum('RULE_BASED', 'AI_MICRO_PROMPT', name='screener_method'), nullable=False),
    sa.Column('screener_response', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('message_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'SUSPENDED', 'EXPIRED', name='conversation_status'), nullable=False),
    sa.Column('consent_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_appointment_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=False),
    sa.Column('completed_booking_count', sa.Integer(), nullable=False),
    sa.Column('calculated_interval_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('blended_interval_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('admin_default_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence', sa.Enum('DEFAULT', 'EMERGING', 'PERSONAL', name='pattern_confidence'), nullable=False),
    sa.Column('outliers_removed', sa.Integer(), nullable=False),
    sa.Column('manual_override_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_phone', 'appointment_type_id', name='uq_pattern_contact_type')
    )
    op.create_table('related_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=False),
    sa.Column('related_appointment_type_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ),
    sa.ForeignKeyConstraint(['related_appointment_type_id'], ['appointment_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_type_id', 'related_appointment_type_id', name='uq_related_service_pair')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='booking_status'), nullable=False),
    sa.Column('price_at_booking', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('ics_sequence', sa.Integer(), nullable=False),
    sa.Column('ics_new_url', sa.String(length=500), nullable=True),
    sa.Column('ics_update_url', sa.String(length=500), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_suspensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('suspension_type', sa.Enum('AUTO_STRIKE', 'AUTO_ABUSIVE', 'MANUAL', name='suspension_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('strike_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_decision', sa.Enum('LIFTED', 'CONFIRMED', 'BANNED', name='review_decision'), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'RESCHEDULED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'STATUS_CHANGED', name='booking_event_type'), nullable=False),
    sa.Column('previous_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previous_status', sa.Enum('SCHEDULED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='booking_status'), nullable=True),
    sa.Column('new_status', sa.Enum('SCHEDULED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='booking_status'), nullable=True),
    sa.Column('changed_by', sa.Enum('USER_SMS', 'ADMIN', 'SCHEDULER', name='changed_by'), nullable=False),
    sa.Column('changed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=False),
    sa.Column('appointment_type_id', sa.UUID(), nullable=False),
    sa.Column('pattern_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_for', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'BOOKED', 'SKIPPED', 'NO_RESPONSE', 'CANCELLED', name='reminder_status'), nullable=False),
    sa.Column('converted_to_booking_id', sa.UUID(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_type_id'], ['appointment_types.id'], ),
    sa.ForeignKeyConstraint(['contact_phone'], ['contacts.phone'], ),
    sa.ForeignKeyConstraint(['converted_to_booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('booking_history')
    op.drop_table('contact_suspensions')
    op.drop_table('bookings')
    op.drop_table('system_settings')
    op.drop_table('related_services')
    op.drop_table('customer_appointment_patterns')
    op.drop_table('conversations')
    op.drop_table('contact_strikes')
    op.drop_table('contact_consent_history')
    op.drop_table('contact_consent')
    op.drop_table('admin_notifications')
    op.drop_table('contacts')
    op.drop_table('blocked_dates')
    op.drop_table('availability_rules')
    op.drop_table('appointment_types')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
